spring:
  datasource:
    url: jdbc:sqlserver://notesservermain.database.windows.net:1433;databaseName=notesDb;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: usernotes
    password: notes@12345
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.SQLServer2012Dialect
server:
  port: 9090
