spring:
  datasource:
    url: jdbc:sqlserver://notesservermain.database.windows.net:1433;databaseName=notesDb;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: usernotes
    password: notes@12345
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.SQLServer2012Dialect
#  security:
#    oauth2:
#      client:
#        provider:
#          azure:
#            issuer-uri: https://login.microsoftonline.com/<YOUR-TENANT-ID-GOES-HERE>/v2.0
#            user-name-attribute: name
#        registration:
#          azure-dev:
#            provider: azure
#            client-id: <YOUR CLIENT ID>
#            client-secret: <YOUR CLIENT SECRET>
#            scope:
#              - openid
#              - email
#              - profile


server:
  port: 8080
